#include<iostream>
using namespace std;

int main()
{
cout << "Enter movie name : ";
string movie;
cin >> movie;

cout << "Enter price of ticket of adult :";
int adult;
cin >> adult;

cout << "Enter price of ticket of child :";
int child;
cin >> child;

cout << "Enter total number of Tickets sold for Adult :";
int sold;
cin >> sold;

cout << "Enter total number of Tickets sold for Children:";
int sold2;
cin >> sold2;

cout << "Enter percentage donated to charity:";
int charity;
cin >> charity;

 int total;
total = (adult*sold)+(child*sold2);

int donation;
donation= (total/100)*10;
int remain;
remain = total-donation;
cout << "Total amount generated by movie:" << total << endl;
cout<< "Donation to charity" << donation  << endl;
cout << "Remaining amount:" << remain; 






}